### ISSUE TITLE
dmesg flooded with 'trying to free an already freed inode'

### ISSUE THREAD

**Issue by Lili1228** [mikaku/Fiwix#110]
Hi, I heard about this project the other day and I immediately wanted to put it to the test. I grabbed 86Box and installed Debian GNU/Linux 2.2, the last one with 2.0 kernel, and tried to make Fiwix from [FiwixOS-3.5-i386.img](https://www.fiwix.org/FiwixOS-3.5-i386.img) work. It didn't boot because I formatted the partition incorrectly, so, on my Linux machine, I copied all the files with `cp -a`, then `mke2fs -E revision=0` and `cp -a` back. What happens next depends on where I try.

Fiwix crashes on QEMU:

```
 cs: 0x0008     eip: 0xc0132ac4 efl: 0x00010286  ss: 0xc0a89b8c esp: 0xffff910c
eax: 0x00000000 ebx: 0xbffffc3c ecx: 0x00000002 edx: 0xbffffc3c
esi: 0xffff910c edi: 0x00000014 esp: 0xc091fea0 ebp: 0xc0959968
 ds: 0x0023      es: 0x0023      fs: 0x0023      gs: 0x0023
Stack:




Kernel backtrace:
num  address range         flag offset     dev   inode      mod section cnt
---- --------------------- ---- ---------- ----- ---------- --- ------- ----
[00] 0x08048000-0x0804f000 r-xp 0x00000000 03:01 14         <0> [text ]  (2)
[01] 0x0804f000-0x08050000 rw-p 0x00006000 03:01 14         <0> [data ]  (2)
[02] 0x08050000-0x08059000 rw-p 0x00000000 00:00 0          <0> [heap ]  (0)
[03] 0x40000000-0x40012000 r-xp 0x00000000 03:01 31365      <0> [text ]  (18)
[04] 0x40012000-0x40014000 rw-p 0x00011000 03:01 31365      <0> [data ]  (18)
[05] 0x40014000-0x40015000 rw-p 0x00000000 00:00 0          <0> [mmap ]  (0)
[06] 0x40017000-0x400ec000 r-xp 0x00000000 03:01 31367      <0> [mmap ]  (2)
[07] 0x400ec000-0x400f0000 rw-p 0x000d4000 03:01 31367      <0> [mmap ]  (2)
[08] 0x400f0000-0x400f4000 rw-p 0x00000000 00:00 0          <0> [mmap ]  (0)
[09] 0x400f7000-0x400ff000 r-xp 0x00000000 03:01 31384      <0> [mmap ]  (2)
[10] 0x400ff000-0x40100000 rw-p 0x00007000 03:01 31384      <0> [mmap ]  (2)
[11] 0x40100000-0x40105000 r-xp 0x00000000 03:01 31382      <0> [mmap ]  (2)
[12] 0x40105000-0x40106000 rw-p 0x00004000 03:01 31382      <0> [mmap ]  (2)
[13] 0x40106000-0x40140000 r-xp 0x00000000 03:01 31369      <0> [mmap ]  (2)
[14] 0x40140000-0x40141000 rw-p 0x00039000 03:01 31369      <0> [mmap ]  (2)
[15] 0xbfffb000-0xc0000000 rwxp 0x00000000 00:00 0          <0> [stack]  (0)

PANIC: in do_page_fault()

**    Safe to Power Off    **
            -or-
** Press Any Key to Reboot **

```

Linux didn't care about moving the machines. No matter where, though, most of the log gets lost in a flood of `WARNING: iput(): trying to free an already freed inode (31367)!` (there are also other inodes in 31xxx range).

Link to my machine: https://lili.lgbt/debian22.7z, root password is `amogus`.

**Comment by mikaku** [comment]
Thank you for your feedback.

Hmm, using Fiwix 3.4 (kernel 1.6.0) seems more stable, so it looks like I introduced a bug somewhere during the 1.7.0 kernel development. I'll try to find in which point I introduced such bug.

In the meantime, please, use [Fiwix-3.4-i386.img](https://www.fiwix.org/old-versions/FiwixOS-3.4/FiwixOS-3.4-i386.img).

EDIT:
This bug was actually fixed here: a52f4affd6e6fbde9a87be1236188313a4a6ee7c. 😃

**Comment by Lili1228** [comment]
Hmm, I can't get master to compile on GCC 2.9.5 in that Debian. I had to patch Makefile because bash-2.03 didn't like `$()` and GCC didn't like some of the options:
```make
TOPDIR = $$(if [ "$$PWD" != "" ] ; then echo $$PWD ; else pwd ; fi)
TMPFILE = $$(mktemp /tmp/temp.XXXXXX)

ARCH =
CFLAGS = -I$(INCLUDE) -O2 -fno-common -ffreestanding -Wall -Wstrict-prototypes #-Wextra -Wno-unused-parameter
```
And with that, it doesn't link:
```make
ld -N -T $(mktemp /tmp/temp.XXXXXX) -m elf_386 kernel/*.o kernel/syscalls/*.o mm/*.o fs/*.o fs/devpts/*.o fs/ext2/*.o fs/iso9660/*.o fs/minix/*.o fs/pipefs/*.o fs/procfs/*.o fs/sockfs/*.o drivers/char/*.o drivers/block/*.o drivers/pci/*.o drivers/video/*.o net/*.o lib/*.o -L/usr/lib/gcc-lib/i386-linux/2.95.2 -lgcc -o fiwix
kernel/multiboot.o: In function `get_last_boot_addr':
kernel/multiboot.o(.text+0x57b): undefined reference to `_end'
kernel/multiboot.o(.text+0x621): undefined reference to `_end'
kernel/process.o: In function `kernel_process':
kernel/process.o(.text+0x61d): undefined reference to `_end'
mm/memory.o: In function `bss_init':
mm/memory.o(.text+0xe2): undefined reference to `_end'
mm/memory.o(.text+0xe7): undefined reference to `_edata'
mm/memory.o(.text+0xef): undefined reference to `_edata'
mm/memory.o: In function `mem_stats':
mm/memory.o(.text+0xd14): undefined reference to `_end'
mm/memory.o(.text+0xd19): undefined reference to `_edata'
mm/memory.o(.text+0xd29): undefined reference to `_edata'
mm/memory.o(.text+0xd2e): undefined reference to `_etext'
mm/memory.o(.text+0xd3e): undefined reference to `_etext'
net/domains.o: In function `net_init':
net/domains.o(.text+0x58): undefined reference to `ext_init'
net/ipv4.o: In function `ipv4_create':
net/ipv4.o(.text+0x89): undefined reference to `ext_open'
net/ipv4.o: In function `ipv4_free':
net/ipv4.o(.text+0xd9): undefined reference to `ext_close'
net/ipv4.o: In function `ipv4_bind':
net/ipv4.o(.text+0x112): undefined reference to `ext_bind'
net/ipv4.o: In function `ipv4_listen':
net/ipv4.o(.text+0x12b): undefined reference to `ext_listen'
net/ipv4.o: In function `ipv4_connect':
net/ipv4.o(.text+0x14a): undefined reference to `ext_connect'
net/ipv4.o: In function `ipv4_accept':
net/ipv4.o(.text+0x169): undefined reference to `ext_accept'
net/ipv4.o: In function `ipv4_sendto':
net/ipv4.o(.text+0x268): undefined reference to `ext_sendto'
net/ipv4.o: In function `ipv4_recvfrom':
net/ipv4.o(.text+0x28c): undefined reference to `ext_recvfrom'
net/ipv4.o: In function `ipv4_read':
net/ipv4.o(.text+0x2aa): undefined reference to `ext_read'
net/ipv4.o: In function `ipv4_write':
net/ipv4.o(.text+0x2c6): undefined reference to `ext_write'
net/ipv4.o: In function `ipv4_ioctl':
net/ipv4.o(.text+0x2e6): undefined reference to `ext_ioctl'
make: *** [all] Error 1
```

**Comment by mikaku** [comment]
Check issue #106 to fix the `ext_*` undefined references.
I've never seen the rest of errors `undefined reference to `_end'` ... make sure all the files are successfully compiled.

Regarding the problems with GCC 2.9.5, I think the option `-ffreestanding` was introduced in newer GCC versions. I guess you can substitute it by `-nostdinc`, `-nostdlib` and `-nostartfiles`.

**Comment by Lili1228** [comment]
Adding these GCC switches didn't help, not that I thought they would since it doesn't compile if it doesn't understand a switch.

**Comment by mikaku** [comment]
Hmm, I think this is just a linking problem. The variables `_end`, `_edata` and `_etext` are defined inside the file `fiwix.ld` which is used by the linker.

Make sure you didn't break anything when trying to adapt the Makefile to your GCC 2.9.5.

**Comment by Lili1228** [comment]
Ah, I see what I did wrong, `TMPFILE := $(shell mktemp /tmp/temp.XXXXXX)` links. But around the time it displays all devices…
```
lp0       0x0378-0x037a     -
ptmx      -                 -   type=UNIX98, ptys=64

Page Fault at 0x00000000 (reading) with error code 0x00 in kernel mode.
Process 'kswapd' with pid 2 in '<NULL>()'.
 cs: 0x0008     eip: 0x00000000 efl: 0x00010286  ss: 0xc0010f0c esp: 0xc012e4be
eax: 0x00000000 ebx: 0xc013ad2c ecx: 0x00000000 edx: 0x2002cb9c
esi: 0xc01954e8 edi: 0xc0192320 esp: 0xc000efbc ebp: 0xc000efe8
 ds: 0x0010      es: 0x0010      fs: 0x0010      gs: 0x0010
Stack:
 c000ef8c c0192320 c0124c39 00000008 00000296 c000ef60 c011143a 0000000e
 c000ef8c c016a6eb 00000296 c013ad2c c01954e8 c010c5ac 00000292 c000ef88
 c012fc0b c000ef80 c0105f69 0000000e c000ef8c c0007e0c c01954e8 c0192320
 00000000 c000efe8 c01006ea 0000000e 00000010 00000010 00000010 00000010
Kernel backtrace:
num  address range         flag offset     dev   inode      mod section cnt
---- --------------------- ---- ---------- ----- ---------- --- ------- ----
[no vma regions]

PANIC: in do_page_fault()
<6>
**    Safe to Power Off    **
            -or-
** Press Any Key to Reboot **
```

**Comment by mikaku** [comment]
The 'master' branch has some networking code unfinished, so:

1. Better comment out the call to `net_init()`:
```diff
diff --git a/mm/swapper.c b/mm/swapper.c
index a8d4d18..ea1f0ee 100644
--- a/mm/swapper.c
+++ b/mm/swapper.c
@@ -45,7 +45,7 @@ int kswapd(void)
 
        /* network */
 #ifdef CONFIG_NET
-       net_init();
+/*     net_init();*/
 #endif /* CONFIG_NET */
 
        /* block devices */
```

2. Also, you might need to comment out the UNIX socket initialitzation:
```diff
diff --git a/net/domains.c b/net/domains.c
index a5af777..90d7957 100644
--- a/net/domains.c
+++ b/net/domains.c
@@ -13,8 +13,8 @@
 
 #ifdef CONFIG_NET
 struct domain_table domains[] = {
-        { AF_UNIX, "AF_UNIX", &unix_ops },
-        { AF_INET, "AF_INET", &ipv4_ops },
+/*        { AF_UNIX, "AF_UNIX", &unix_ops },*/
+/*        { AF_INET, "AF_INET", &ipv4_ops },*/
         { 0, 0, 0 }
 };
```

Sorry for these inconveniences, the 'master'  branch is WIP right now.
Let me know if that worked for you.

**Comment by Lili1228** [comment]
It compiles, it goes through the devices list, but then init immediately dies, apparent by a message `WARNING: the last user process has exited. The kernel will stop itself.`

**Comment by mikaku** [comment]
I'm using your virtual machine with the same changes in the 'master' branch and it boots finely:

<img width="1024" height="831" alt="Image" src="https://github.com/user-attachments/assets/13bb77c6-216f-4c93-89fc-5a4c8aeb7a0e" />

**Comment by Lili1228** [comment]
Well dangit >.< I don't know what I did wrong then

**Comment by mikaku** [comment]
I'm using a GCC 4.7.4 compiler, not your GCC 2.9.5, perhaps this is the difference?
If you can connect via [IRC Libera.Chat](https://web.libera.chat/) to the #fiwix channel, I think that would be easier to fix.

**Comment by mikaku** [comment]
I think I have found the problem. For an unknown reason, the code in `init_trampoline()` is not well converted to Assembly during the second call to `SYS_dup()`:

https://github.com/mikaku/Fiwix/blob/58e1b84e14b1d6cc46b885e382759240b294ff07/kernel/init.c#L29-L38

 The `%eax` register is not loaded with the number of the function call, probably as a result of a bad optimization.

If you insert a different call between the two 'SYS_dup()' lines, then the compiler is forced to abandon optimization and the `%eax` register is loaded with the right value:

```C
[...]
        USER_SYSCALL(SYS_dup, 0, NULL, NULL);                        /* stdin */
        USER_SYSCALL(SYS_getpid, 0, NULL, NULL);
        USER_SYSCALL(SYS_dup, 0, NULL, NULL);                        /* stdout */
[...]
```
